server:
  port: 6464

spring:
  application:
    name: web-application

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true
    